DROP TABLE REZERVARE CASCADE CONSTRAINTS;
DROP TABLE IMPRUMUT CASCADE CONSTRAINTS;
DROP TABLE CARTE_AUTOR CASCADE CONSTRAINTS; -- Tabel asociativ
DROP TABLE EXEMPLAR CASCADE CONSTRAINTS;
DROP TABLE CARTE CASCADE CONSTRAINTS;
DROP TABLE UTILIZATOR CASCADE CONSTRAINTS;
DROP TABLE AUTOR CASCADE CONSTRAINTS;
DROP TABLE EDITURA CASCADE CONSTRAINTS;

DROP SEQUENCE seq_id_utilizator_unic;


CREATE SEQUENCE seq_id_utilizator_unic
    START WITH 1
    INCREMENT BY 1;

CREATE TABLE EDITURA (
    id_editura NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nume VARCHAR2(100) NOT NULL,
    oras VARCHAR2(100),
    an_infiintare NUMBER(4),
    CONSTRAINT uq_editura_nume UNIQUE (nume)
);

CREATE TABLE AUTOR (
    id_autor NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nume VARCHAR2(100) NOT NULL,
    prenume VARCHAR2(100),
    nationalitate VARCHAR2(50),
    data_nasterii DATE
);

-- UTILIZATOR va folosi secvența dedicată 'seq_id_utilizator_unic'
CREATE TABLE UTILIZATOR (
    id_utilizator INT DEFAULT seq_id_utilizator_unic.NEXTVAL PRIMARY KEY,
    nume_complet VARCHAR2(100) NOT NULL,
    email VARCHAR2(100) NOT NULL,
    categorie VARCHAR2(20) NOT NULL,
    data_inregistrare DATE DEFAULT SYSDATE,
    are_intarzieri NUMBER(1) DEFAULT 0,
    CONSTRAINT uq_utilizator_email UNIQUE (email),
    CONSTRAINT chk_utilizator_categorie CHECK (categorie IN ('student', 'cadru_didactic', 'extern', 'pensionar')),
    CONSTRAINT chk_utilizator_intarzieri CHECK (are_intarzieri IN (0, 1))
);

CREATE TABLE CARTE (
    id_carte NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_editura INT NOT NULL,
    titlu VARCHAR2(255) NOT NULL,
    an_aparitie NUMBER(4),
    domeniu VARCHAR2(100),
    limba VARCHAR2(50) DEFAULT 'Romana',
    CONSTRAINT fk_carte_editura FOREIGN KEY (id_editura) REFERENCES EDITURA(id_editura)
);

CREATE TABLE CARTE_AUTOR (
    id_carte INT NOT NULL,
    id_autor INT NOT NULL,
    rol_autor VARCHAR2(50) DEFAULT 'Autor principal',
    CONSTRAINT pk_carte_autor PRIMARY KEY (id_carte, id_autor),
    CONSTRAINT fk_ca_carte FOREIGN KEY (id_carte) REFERENCES CARTE(id_carte) ON DELETE CASCADE,
    CONSTRAINT fk_ca_autor FOREIGN KEY (id_autor) REFERENCES AUTOR(id_autor) ON DELETE CASCADE
);

CREATE TABLE EXEMPLAR (
    id_exemplar NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, -- Folosim IDENTITY aici
    id_carte INT NOT NULL,
    stare VARCHAR2(20) DEFAULT 'buna',
    este_disponibil NUMBER(1) DEFAULT 1,
    locatie VARCHAR2(50),
    CONSTRAINT fk_exemplar_carte FOREIGN KEY (id_carte) REFERENCES CARTE(id_carte),
    CONSTRAINT chk_exemplar_stare CHECK (stare IN ('noua', 'buna', 'uzata', 'deteriorata', 'pierduta')),
    CONSTRAINT chk_exemplar_disponibil CHECK (este_disponibil IN (0, 1))
);

CREATE TABLE IMPRUMUT (
    id_imprumut NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_utilizator INT NOT NULL,
    id_exemplar INT NOT NULL,
    data_imprumut DATE DEFAULT SYSDATE NOT NULL,
    data_scadenta DATE NOT NULL,
    data_returnare DATE,
    penalizare_aplicata NUMBER(1) DEFAULT 0,
    CONSTRAINT uq_imprumut_exemplar_activ UNIQUE (id_exemplar),
    CONSTRAINT fk_imprumut_utilizator FOREIGN KEY (id_utilizator) REFERENCES UTILIZATOR(id_utilizator),
    CONSTRAINT fk_imprumut_exemplar FOREIGN KEY (id_exemplar) REFERENCES EXEMPLAR(id_exemplar),
    CONSTRAINT chk_imprumut_date CHECK (data_returnare IS NULL OR data_returnare >= data_imprumut),
    CONSTRAINT chk_imprumut_scadenta CHECK (data_scadenta > data_imprumut),
    CONSTRAINT chk_imprumut_penalizare CHECK (penalizare_aplicata IN (0, 1))
);

CREATE TABLE REZERVARE (
    id_rezervare NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, -- Folosim IDENTITY aici
    id_utilizator INT NOT NULL,
    id_exemplar INT NOT NULL,
    data_rezervare DATE DEFAULT SYSDATE NOT NULL,
    status VARCHAR2(20) DEFAULT 'activa',
     CONSTRAINT fk_rezervare_utilizator FOREIGN KEY (id_utilizator) REFERENCES UTILIZATOR(id_utilizator),
    CONSTRAINT fk_rezervare_exemplar FOREIGN KEY (id_exemplar) REFERENCES EXEMPLAR(id_exemplar),
    CONSTRAINT chk_rezervare_status CHECK (status IN ('activa', 'anulata_utilizator', 'anulata_sistem', 'onorata', 'expirata')),
    CONSTRAINT uq_rezervare_activa_exemplar UNIQUE (id_exemplar, status)
);


INSERT INTO EDITURA (nume, oras, an_infiintare) VALUES ('Humanitas', 'Bucuresti', 1990);
INSERT INTO EDITURA (nume, oras, an_infiintare) VALUES ('Polirom', 'Iasi', 1995);
INSERT INTO EDITURA (nume, oras, an_infiintare) VALUES ('RAO', 'Bucuresti', 1993);
INSERT INTO EDITURA (nume, oras, an_infiintare) VALUES ('Curtea Veche', 'Bucuresti', 1998);
INSERT INTO EDITURA (nume, oras, an_infiintare) VALUES ('Litera', 'Bucuresti', 1989);
INSERT INTO EDITURA (nume, oras, an_infiintare) VALUES ('Nemira', 'Bucuresti', 1991);

SELECT * FROM EDITURA;

INSERT INTO AUTOR (nume, prenume, nationalitate, data_nasterii)
VALUES ('Eminescu', 'Mihai', 'Romana', TO_DATE('1850-01-15', 'YYYY-MM-DD'));
INSERT INTO AUTOR (nume, prenume, nationalitate, data_nasterii)
VALUES ('Cartarescu', 'Mircea', 'Romana', TO_DATE('1956-06-01', 'YYYY-MM-DD'));
INSERT INTO AUTOR (nume, prenume, nationalitate, data_nasterii)
VALUES ('Orwell', 'George', 'Britanica', TO_DATE('1903-06-25', 'YYYY-MM-DD'));
INSERT INTO AUTOR (nume, prenume, nationalitate, data_nasterii)
VALUES ('Liiceanu', 'Gabriel', 'Romana', TO_DATE('1942-05-23', 'YYYY-MM-DD'));
INSERT INTO AUTOR (nume, prenume, nationalitate, data_nasterii)
VALUES ('Rowling', 'J.K.', 'Britanica', TO_DATE('1965-07-31', 'YYYY-MM-DD'));
INSERT INTO AUTOR (nume, prenume, nationalitate, data_nasterii)
VALUES( 'Rebreanu', 'Liviu', 'Romana', TO_DATE('1885-11-27', 'YYYY-MM-DD'));
INSERT INTO AUTOR (nume, prenume, nationalitate, data_nasterii)
VALUES( 'Asimov', 'Isaac', 'Americana', TO_DATE('1920-01-02', 'YYYY-MM-DD'));

SELECT * FROM AUTOR;

INSERT INTO UTILIZATOR (nume_complet, email, categorie, data_inregistrare, are_intarzieri)
VALUES ('Popescu Ion', 'ion.popescu@email.com', 'student', TO_DATE('2023-01-10', 'YYYY-MM-DD'), 0);
INSERT INTO UTILIZATOR (nume_complet, email, categorie, data_inregistrare, are_intarzieri)
VALUES ('Ionescu Ana', 'ana.ionescu@email.com', 'cadru_didactic', TO_DATE('2022-11-05', 'YYYY-MM-DD'), 1);
INSERT INTO UTILIZATOR (nume_complet, email, categorie, data_inregistrare, are_intarzieri)
VALUES ('Marinescu Vasile', 'vasile.marinescu@email.com', 'extern', TO_DATE('2023-03-15', 'YYYY-MM-DD'), 0);
INSERT INTO UTILIZATOR (nume_complet, email, categorie, data_inregistrare, are_intarzieri)
VALUES ('Georgescu Maria', 'maria.g@email.com', 'student', TO_DATE('2023-05-20', 'YYYY-MM-DD'), 0);
INSERT INTO UTILIZATOR (nume_complet, email, categorie, data_inregistrare, are_intarzieri)
VALUES ('Radulescu Andrei', 'andrei.r@email.com', 'pensionar', TO_DATE('2021-07-01', 'YYYY-MM-DD'), 0);

SELECT * FROM UTILIZATOR;

INSERT INTO CARTE (id_editura, titlu, an_aparitie, domeniu, limba)
VALUES (1, 'Jurnalul de la Paltinis', 1983, 'Filosofie', 'Romana');
INSERT INTO CARTE (id_editura, titlu, an_aparitie, domeniu, limba)
VALUES (2, 'Poezii Eminescu', 1980, 'Poezie', 'Romana');
INSERT INTO CARTE (id_editura, titlu, an_aparitie, domeniu, limba)
VALUES (3, 'Harry Potter si Piatra Filozofala', 2001, 'Fantasy', 'Romana');
INSERT INTO CARTE (id_editura, titlu, an_aparitie, domeniu, limba)
VALUES (1, 'Despre limita', 1994, 'Eseu', 'Romana');
INSERT INTO CARTE (id_editura, titlu, an_aparitie, domeniu, limba)
VALUES (5, 'Ion', 1920, 'Roman realist', 'Romana');
INSERT INTO CARTE (id_editura, titlu, an_aparitie, domeniu, limba)
VALUES( 1, 'Nostalgia', 1993, 'Proza', 'Romana');
INSERT INTO CARTE (id_editura, titlu, an_aparitie, domeniu, limba)
VALUES( 2, 'Fundatia', 1951, 'SF', 'Engleza');

SELECT * FROM CARTE;

--caut id urile reale din tabela autor si carte
SELECT id_autor, nume, prenume FROM AUTOR ORDER BY id_autor;
SELECT id_carte, titlu FROM CARTE ORDER BY id_carte;

INSERT INTO CARTE_AUTOR (id_carte, id_autor, rol_autor) VALUES (2, 4, 'Autor principal');
INSERT INTO CARTE_AUTOR (id_carte, id_autor, rol_autor) VALUES (6, 4, 'Autor principal');
INSERT INTO CARTE_AUTOR (id_carte, id_autor, rol_autor) VALUES (4, 1, 'Autor principal');
INSERT INTO CARTE_AUTOR (id_carte, id_autor, rol_autor) VALUES (5, 5, 'Autor principal');
INSERT INTO CARTE_AUTOR (id_carte, id_autor, rol_autor) VALUES (7, 6, 'Autor principal');
INSERT INTO CARTE_AUTOR (id_carte, id_autor, rol_autor) VALUES (2, 2, 'Prefata');
INSERT INTO CARTE_AUTOR (id_carte, id_autor, rol_autor) VALUES (6, 7, 'Autor principal');
INSERT INTO CARTE_AUTOR (id_carte, id_autor, rol_autor) VALUES (7, 2, 'Autor principal');
INSERT INTO CARTE_AUTOR (id_carte, id_autor, rol_autor) VALUES (4, 4, 'Studiu critic');
INSERT INTO CARTE_AUTOR (id_carte, id_autor, rol_autor) VALUES (7, 4, 'Studiu critic');

SELECT * FROM CARTE_AUTOR;

INSERT INTO EXEMPLAR (id_carte, stare, este_disponibil, locatie)
VALUES (1, 'buna', 1, 'Raft F1');
INSERT INTO EXEMPLAR (id_carte, stare, este_disponibil, locatie)
VALUES (6, 'uzata', 0, 'Imprumut');
INSERT INTO EXEMPLAR (id_carte, stare, este_disponibil, locatie)
VALUES (5, 'noua', 1, 'Raft P1');
INSERT INTO EXEMPLAR (id_carte, stare, este_disponibil, locatie)
VALUES (4, 'buna', 1, 'Raft H7');
INSERT INTO EXEMPLAR (id_carte, stare, este_disponibil, locatie)
VALUES (2, 'deteriorata', 0, 'Reparatii');

SELECT * FROM EXEMPLAR;

UPDATE EXEMPLAR SET este_disponibil = 0 WHERE id_exemplar = 1;
INSERT INTO IMPRUMUT (id_utilizator, id_exemplar, data_imprumut, data_scadenta)
VALUES (1, 4, SYSDATE - 5, SYSDATE + 9);

UPDATE EXEMPLAR SET este_disponibil = 0 WHERE id_exemplar = 9;
INSERT INTO IMPRUMUT (id_utilizator, id_exemplar, data_imprumut, data_scadenta, data_returnare, penalizare_aplicata)
VALUES (2, 5, SYSDATE - 10, SYSDATE - 3, SYSDATE - 2, 1);
UPDATE EXEMPLAR SET este_disponibil = 1, stare = 'uzata' WHERE id_exemplar = 9;

INSERT INTO EXEMPLAR (id_carte, stare, este_disponibil, locatie) VALUES (4, 'buna', 1, 'Raft E3');
UPDATE EXEMPLAR SET este_disponibil = 0 WHERE id_exemplar = 16;
INSERT INTO IMPRUMUT (id_utilizator, id_exemplar, data_imprumut, data_scadenta)
VALUES (3, 3, SYSDATE - 2, SYSDATE + 12);

INSERT INTO EXEMPLAR (id_carte, stare, este_disponibil, locatie) VALUES (7, 'noua', 1, 'Raft SF1');
UPDATE EXEMPLAR SET este_disponibil = 0 WHERE id_exemplar = 10;
INSERT INTO IMPRUMUT (id_utilizator, id_exemplar, data_imprumut, data_scadenta)
VALUES (4, 1, SYSDATE - 20, SYSDATE - 6);
UPDATE EXEMPLAR SET este_disponibil = 1 WHERE id_exemplar = 10;

INSERT INTO IMPRUMUT (id_utilizator, id_exemplar, data_imprumut, data_scadenta)
VALUES (5, 2, SYSDATE - 1, SYSDATE + 13);
UPDATE EXEMPLAR SET este_disponibil = 0 WHERE id_exemplar = 21;

SELECT * FROM IMPRUMUT;

INSERT INTO REZERVARE (id_utilizator, id_exemplar, data_rezervare, status)
VALUES (2, 2, SYSDATE - 1, 'activa');
INSERT INTO REZERVARE (id_utilizator, id_exemplar, data_rezervare, status)
VALUES (1, 1, SYSDATE, 'activa');
INSERT INTO REZERVARE (id_utilizator, id_exemplar, data_rezervare, status)
VALUES (4, 4, SYSDATE - 7, 'onorata');
INSERT INTO REZERVARE (id_utilizator, id_exemplar, data_rezervare, status)
VALUES (3, 5, SYSDATE - 3, 'anulata_utilizator');
INSERT INTO REZERVARE (id_utilizator, id_exemplar, data_rezervare, status)
VALUES (5, 3, SYSDATE, 'activa');

SELECT * FROM REZERVARE;


---------------12----------

-----Afișați numele complet, emailul și categoria utilizatorilor care au cel puțin un
-- împrumut activ (nereturnat) pentru o carte publicată de o editură din 'Bucuresti'.
-- Se vor afișa doar utilizatorii care au exact un astfel de împrumut activ.
-- Se va ordona după numele complet al utilizatorului.
SELECT
    u.nume_complet,
    u.email,
    u.categorie
FROM
    UTILIZATOR u
WHERE
    EXISTS (
        SELECT 1
        FROM IMPRUMUT i
        JOIN EXEMPLAR ex ON i.id_exemplar = ex.id_exemplar
        JOIN CARTE c ON ex.id_carte = c.id_carte
        JOIN EDITURA e ON c.id_editura = e.id_editura
        WHERE i.id_utilizator = u.id_utilizator
          AND e.oras = 'Bucuresti'
          AND i.data_returnare IS NULL
    )
    AND 1 = ( -- Subcerere sincronizata pentru a numara imprumuturile active de la edituri din Bucuresti
        SELECT COUNT(*)
        FROM IMPRUMUT i_count
        JOIN EXEMPLAR ex_count ON i_count.id_exemplar = ex_count.id_exemplar
        JOIN CARTE c_count ON ex_count.id_carte = c_count.id_carte
        JOIN EDITURA e_count ON c_count.id_editura = e_count.id_editura
        WHERE i_count.id_utilizator = u.id_utilizator
          AND e_count.oras = 'Bucuresti'
          AND i_count.data_returnare IS NULL
    )
ORDER BY
    u.nume_complet;


UPDATE EXEMPLAR  set este_disponibil = 0  where este_disponibil = 0;
UPDATE EXEMPLAR SET este_disponibil = 1 WHERE id_exemplar = 9;

----Afișați titlul cărților, numele editurii și numărul total de exemplare disponibile pentru fiecare carte,
-- dar numai pentru acele cărți care au un număr de exemplare disponibile mai mare decât media numărului de exemplare
-- disponibile per carte din întreaga bibliotecă. Ordonare descrescătoare după numărul de exemplare disponibile.

SELECT
    c.titlu AS TitluCarte,
    ed.nume AS NumeEditura,
    COUNT(CASE WHEN ex.este_disponibil = 1 THEN ex.id_exemplar END) AS NumarExemplareDisponibile
FROM
    CARTE c
JOIN
    EDITURA ed ON c.id_editura = ed.id_editura
JOIN
    EXEMPLAR ex ON c.id_carte = ex.id_carte
GROUP BY
    c.titlu, ed.nume, c.id_carte
HAVING
    COUNT(CASE WHEN ex.este_disponibil = 1 THEN ex.id_exemplar END) > (
        SELECT AVG(NumarDisponibilePeCarte)
        FROM (
            SELECT id_carte, COUNT(CASE WHEN este_disponibil = 1 THEN id_exemplar END) AS NumarDisponibilePeCarte
            FROM EXEMPLAR
            GROUP BY id_carte
        ) MediiPeCarte
    )
ORDER BY
    NumarExemplareDisponibile DESC;


--Afișați numele utilizatorului, titlul cărții împrumutate, data împrumutului formatată,
-- și o coloană 'Status Imprumut' care indică dacă împrumutul este 'Returnat la timp', 'Returnat cu intarziere',
-- 'In curs - Termen depasit' sau 'In curs - In termen'. Se va afișa și descrierea penalizării folosind DECODE.
-- Pentru împrumuturile nereturnate, se va considera data curentă pentru evaluarea depășirii termenului.
-- Folosiți NVL pentru a afișa 'Nereturnat' în locul unei date de returnare goale. Ordonare după numele utilizatorului
-- și apoi data împrumutului.

SELECT
    u.nume_complet AS NumeUtilizator,
    c.titlu AS TitluCarte,
    TO_CHAR(i.data_imprumut, 'DD-Mon-YYYY HH24:MI') AS DataImprumutFormatata,
    NVL(TO_CHAR(i.data_returnare, 'DD-Mon-YYYY'), 'Nereturnat') AS DataReturnare,
    CASE
        WHEN i.data_returnare IS NOT NULL AND i.data_returnare <= i.data_scadenta THEN 'Returnat la timp'
        WHEN i.data_returnare IS NOT NULL AND i.data_returnare > i.data_scadenta THEN 'Returnat cu intarziere'
        WHEN i.data_returnare IS NULL AND SYSDATE > i.data_scadenta THEN 'In curs - Termen depasit'
        ELSE 'In curs - In termen'
    END AS StatusImprumut,
    DECODE(i.penalizare_aplicata, 1, 'S-a aplicat penalizare', 0, 'Fara penalizare', 'Necunoscut') AS DescrierePenalizare,
    SUBSTR(u.email, 1, INSTR(u.email, '@') - 1) AS UtilizatorEmailLocalPart ---Extrage partea din email până la @
FROM
    IMPRUMUT i
JOIN
    UTILIZATOR u ON i.id_utilizator = u.id_utilizator
JOIN
    EXEMPLAR ex ON i.id_exemplar = ex.id_exemplar
JOIN
    CARTE c ON ex.id_carte = c.id_carte
ORDER BY
    u.nume_complet, i.data_imprumut;

--Folosind o clauză WITH pentru a preselecta cărțile scrise de autori români,
-- afișați numele complet al autorilor și numărul total de cărți scrise de aceștia care au fost
-- publicate de edituri înființate după anul 1990. Se vor considera doar autorii care au cel puțin o astfel de carte.
-- Rezultatele vor fi obținute dintr-o subcerere în clauza FROM care combină autorii cu cărțile lor și editurile relevante.


WITH AutoriRomaniCarti AS (
    SELECT
        a.id_autor,
        a.nume || ' ' || a.prenume AS NumeCompletAutor,
        ca.id_carte
    FROM
        AUTOR a
    JOIN
        CARTE_AUTOR ca ON a.id_autor = ca.id_autor
    WHERE
        LOWER(a.nationalitate) = 'romana'
)
SELECT
    StatisticiAutori.NumeAutor,
    StatisticiAutori.NumarCartiPublicatePost1990
FROM (
    SELECT
        arc.NumeCompletAutor AS NumeAutor,
        COUNT(DISTINCT c.id_carte) AS NumarCartiPublicatePost1990
    FROM
        AutoriRomaniCarti arc
    JOIN
        CARTE c ON arc.id_carte = c.id_carte
    JOIN
        EDITURA e ON c.id_editura = e.id_editura
    WHERE
        e.an_infiintare > 1990
    GROUP BY
        arc.NumeCompletAutor
    HAVING
        COUNT(DISTINCT c.id_carte) > 0
) StatisticiAutori
ORDER BY
    StatisticiAutori.NumarCartiPublicatePost1990 DESC;

--Afișați pentru fiecare utilizator: numele complet, categoria (cu o descriere extinsă folosind DECODE), numărul
-- total de rezervări active și vechimea contului în luni. Includeți și prima literă a prenumelui și numele de familie.
-- Se vor afișa toți utilizatorii, chiar dacă nu au rezervări active (numărul de rezervări va fi 0).
-- Ordonare după vechimea contului descrescător, apoi după nume.

SELECT
    SUBSTR(u.nume_complet, INSTR(u.nume_complet, ' ') + 1) || ', ' || SUBSTR(u.nume_complet, 1, 1) || '.' AS NumeFormatat,
    DECODE(u.categorie,
           'student', 'Student Universitar',
           'cadru_didactic', 'Cadru Didactic Universitar',
           'extern', 'Utilizator Extern Bibliotecii',
           'pensionar', 'Utilizator Pensionar',
           'Categorie Necunoscuta') AS CategorieExtinsa,
    NVL(RezervariUtilizator.NumarRezervariActive, 0) AS TotalRezervariActive,
    FLOOR(MONTHS_BETWEEN(SYSDATE, u.data_inregistrare)) AS VechimeContLuni,
    TO_CHAR(u.data_inregistrare, 'Month YYYY', 'NLS_DATE_LANGUAGE=Romanian') AS LunaAnInregistrare
FROM
    UTILIZATOR u
LEFT JOIN (
    SELECT
        id_utilizator,
        COUNT(id_rezervare) AS NumarRezervariActive
    FROM
        REZERVARE
    WHERE
        status = 'activa'
    GROUP BY
        id_utilizator
) RezervariUtilizator ON u.id_utilizator = RezervariUtilizator.id_utilizator
ORDER BY
    VechimeContLuni DESC, u.nume_complet;

-----------------13-----------------

SELECT * FROM REZERVARE;
--Elimină rezervările pentru utilizatorii care nu au niciun împrumut activ.

DELETE FROM REZERVARE
WHERE id_utilizator IN (
    SELECT u.id_utilizator
    FROM UTILIZATOR u
    WHERE NOT EXISTS (
        SELECT 1
        FROM IMPRUMUT i
        WHERE i.id_utilizator = u.id_utilizator
          AND i.data_returnare IS NULL
    )
);

SELECT * FROM EXEMPLAR;
--Actualizează locația exemplarelor ('Depozit Arhiva')
-- pentru toate cărțile publicate înainte de anul 2000, care nu sunt împrumutate și nu sunt rezervate activ.
UPDATE EXEMPLAR ex
SET ex.locatie = 'Depozit Arhiva'
WHERE ex.id_carte IN (
    SELECT c.id_carte
    FROM CARTE c
    WHERE c.an_aparitie < 2000
)
AND ex.este_disponibil = 1
AND ex.id_exemplar NOT IN (
    SELECT r.id_exemplar
    FROM REZERVARE r
    WHERE r.status = 'activa'
);

SELECT * FROM EXEMPLAR;


SELECT * FROM AUTOR;

--Șterge toți autorii care nu au nicio carte listată în tabela
-- CARTE_AUTOR și a căror dată de naștere este înainte de 1 ianuarie 1950 (autori vechi, fără opere înregistrate).

DELETE FROM AUTOR a
WHERE a.data_nasterii < TO_DATE('1950-01-01', 'YYYY-MM-DD')
AND a.id_autor NOT IN (
    SELECT DISTINCT ca.id_autor
    FROM CARTE_AUTOR ca
);

SELECT * FROM CARTE;

---Marchează cărţile clasice (apărute înainte de 1950) cu domeniul „Clasic”

UPDATE CARTE
SET domeniu = 'Clasic'
WHERE an_aparitie < 1950;

SELECT * FROM CARTE;

SELECT * FROM EXEMPLAR;

--Marchează drept „pierdute” și indisponibile exemplarele împrumutate cu termen depășit de peste 6 de zile.

UPDATE EXEMPLAR ex
SET ex.stare = 'pierduta',
    ex.este_disponibil = 0
WHERE ex.id_exemplar IN (
    SELECT i.id_exemplar
    FROM IMPRUMUT i
    WHERE i.data_returnare IS NULL
      AND i.data_scadenta < SYSDATE - 6
);

SELECT * FROM CARTE;
--Șterge cărțile care nu mai au niciun exemplar asociat.

DELETE FROM CARTE
WHERE id_carte NOT IN (
    SELECT DISTINCT id_carte
    FROM EXEMPLAR
);



----14. Crearea unei vizualizări complexe. Dați un exemplu de operație
-- LMD permisă pe vizualizarea respectivă și un exemplu de operație LMD nepermisă.

CREATE OR REPLACE VIEW V_IMPRUMUT_UTILIZATOR AS
SELECT
  i.id_imprumut,
  i.id_utilizator,
  i.id_exemplar,
  i.data_imprumut,
  i.data_scadenta,
  i.data_returnare,
  i.penalizare_aplicata,
  u.nume_complet,
  u.email,
  -- Câmp calculat: numărul de zile cu care s-a depășit data_scadenta
  CASE
    WHEN i.data_returnare IS NULL
         AND SYSDATE > i.data_scadenta
      THEN TRUNC(SYSDATE - i.data_scadenta)
    WHEN i.data_returnare IS NOT NULL
         AND i.data_returnare > i.data_scadenta
      THEN TRUNC(i.data_returnare - i.data_scadenta)
    ELSE 0
  END AS zile_intarziere
FROM IMPRUMUT i
JOIN UTILIZATOR u
  ON i.id_utilizator = u.id_utilizator;


--Operație LMD permisă:
UPDATE V_IMPRUMUT_UTILIZATOR
SET data_returnare = SYSDATE,
    penalizare_aplicata = 1
WHERE id_imprumut = 42;

select *
from V_IMPRUMUT_UTILIZATOR;


--Exemplu de operație LMD nepermisă pe același view:
--UPDATE V_IMPRUMUT_UTILIZATOR
--SET nume_complet = 'Ionescu Gabriel'
--WHERE id_imprumut = 42;



--Cerere cu outer join pe cel puțin 4 tabele
--Afișează toţi utilizatorii din bibliotecă împreună cu
-- informațiile despre cartea pe care au împrumutat-o (titlu), cu
-- locația exemplarului și cu numele editurii. Dacă un utilizator nu a făcut niciun împrumut, rândul
-- va apărea oricum, dar coloanele legate de împrumut, exemplare, carte şi editură vor fi NULL.

SELECT
    u.id_utilizator,
    u.nume_complet,
    i.id_imprumut,
    ex.id_exemplar,
    c.titlu AS titlu_carte,
    ex.locatie       AS locatie_exemplar,
    e.nume           AS nume_editura
FROM UTILIZATOR u
LEFT OUTER JOIN IMPRUMUT     i  ON u.id_utilizator = i.id_utilizator
LEFT OUTER JOIN EXEMPLAR     ex ON i.id_exemplar   = ex.id_exemplar
LEFT OUTER JOIN CARTE        c  ON ex.id_carte      = c.id_carte
LEFT OUTER JOIN EDITURA      e  ON c.id_editura     = e.id_editura
ORDER BY u.nume_complet;


--Cerere care foloseşte operația “division” (÷):
--Găsește utilizatorii (id și nume) care au împrumutat fiecare carte publicată de editura Humanitas.

SELECT
    u.id_utilizator,
    u.nume_complet
FROM UTILIZATOR u
WHERE NOT EXISTS (
    -- Subinterogarea 1: ia toate cărțile publicate de "Humanitas"
    SELECT c.id_carte
    FROM CARTE c
    JOIN EDITURA e
      ON c.id_editura = e.id_editura
    WHERE e.nume = 'Humanitas'
      AND NOT EXISTS (
        -- Subinterogarea 2: să existe un împrumut făcut de u pentru fiecare id_carte
        SELECT 1
        FROM IMPRUMUT i
        JOIN EXEMPLAR ex
          ON i.id_exemplar = ex.id_exemplar
        WHERE i.id_utilizator = u.id_utilizator
          AND ex.id_carte      = c.id_carte
      )
)
ORDER BY u.nume_complet;


--Afișează primele 3 titluri de carte care au fost împrumutate de cele mai multe ori (adică titlurile pentru care numărul
-- total de împrumuturi este în top 3). Pentru fiecare titlu, precizează și numărul total de împrumuturi.
SELECT *
FROM (
    SELECT
        c.titlu,
        COUNT(*) AS numar_imprumuturi
    FROM IMPRUMUT i
    JOIN EXEMPLAR ex
      ON i.id_exemplar = ex.id_exemplar
    JOIN CARTE c
      ON ex.id_carte    = c.id_carte
    GROUP BY c.titlu
    ORDER BY COUNT(*) DESC
)
WHERE ROWNUM <= 3;













